<?php
//error_reporting(-1);
//ini_set('display_errors', 'On');
//set_error_handler("var_dump");
session_start();

ob_start();

require_once "../../../assets/support/inc.all.php";



$title='New Work Order Create';

do_calander('#po_date');

do_calander('#wo_del_date');

do_calander('#quotation_date');


$table_master='purchase_master';

$table_details='purchase_invoice';

$unique='po_no';



if($_GET['mhafuz']==2)
unset($_SESSION[$unique]);
function next_po_no()
{
 $sdate = time();
 $e_ch = date('y',$sdate).$_SESSION['user']['id'].'99999';
 $s_ch = date('y',$sdate).$_SESSION['user']['id'].'00000';
 $unit = 1;
 $sql = 'select max(po_no) from purchase_master where po_no between "'.$s_ch.'" and "'.$e_ch.'" ';
 $query = mysql_query($sql);
 
 $data=mysql_fetch_row($query);
if($data[0]<$s_ch)
$ch_no = $s_ch+$unit;
else
$ch_no = $data[0]+$unit;
 return $ch_no;
}


$$unique=$_SESSION[$unique];



if(isset($_POST['delete']))

{

		$crud   = new crud($table_master);

		$condition=$unique."=".$$unique;		

		$crud->delete($condition);

		$crud   = new crud($table_details);

		$condition=$unique."=".$$unique;		

		$crud->delete_all($condition);

		unset($$unique);

		unset($_SESSION[$unique]);

		$type=1;

		$msg='Successfully Deleted.';

}



if($_GET['del']>0)

{

		$crud   = new crud($table_details);

		$condition="id=".$_GET['del'];		

		$crud->delete_all($condition);

		$type=1;

		$msg='Successfully Deleted.';

}

if(isset($_POST['confirmm']))

{

		unset($_POST);

		$_POST[$unique]=$$unique;

		$_POST['entry_by']=$_SESSION['user']['id'];

		$_POST['entry_at']=date('Y-m-d H:i:s');

		$_POST['status']='UNCHECKED WO';

		$crud   = new crud($table_master);

		$crud->update($unique);
		
		$emailId = 'faruk@erp.com.bd';
		//$emailId = 'ashiq.rony@gmail.com';
		if($emailId!=''){
				$to = $emailId;
				$subject = "New purchase order";
				$txt = "<p>Dear Sir,</p>
				<p>A new purchase order has been created. Need your approval. PO No is: <b>".$$unique."<b></p>
				<p>Prepared By- <b>".find_a_field('user_activity_management','fname','user_id='.$_SESSION['user']['id'])."<b></p>
				<p>This EMAIL is automatically generated by ERP Software.</p>";
				
				$headers  = 'MIME-Version: 1.0' . "\n";
				$headers .= 'Cc: omar.fk15@gmail.com' . "\n";
				$headers .= 'Content-type:text/html;charset=UTF-8' . "\n";
								
				mail($to,$subject,$txt,$headers);
				//echo 'OK '.$to;
			}


		unset($$unique);

		unset($_SESSION[$unique]);

		$type=1;

		$msg='Successfully Forwarded for Approval.';

}



if(isset($_POST['add'])&&($_POST[$unique]>0))

{
$crud   = new crud($table_master);
		$_POST['entry_by']=$_SESSION['user']['id'];
		$_POST['entry_at']=date('Y-m-d H:i:s');
		$_POST['edit_by']=$_SESSION['user']['id'];
		$_POST['edit_at']=date('Y-m-d H:i:s');
		
		if(!isset($_SESSION[$unique])) {


		$$unique = $_POST[$unique] = $_SESSION[$unique] = next_po_no();
  		$crud->insert();
		

		if($_FILES['qoutationDoc']['tmp_name']!=''){ 
			$file_temp = $_FILES['qoutationDoc']['tmp_name'];
			$folder = "../../po_documents/qoutationDoc/";
			move_uploaded_file($file_temp, $folder.$$unique.".pdf");}
		
		//$$unique=$_SESSION[$unique];

		}

		else {
		$crud->update($unique);

		if($_FILES['qoutationDoc']['tmp_name']!=''){ 
			$file_temp = $_FILES['qoutationDoc']['tmp_name'];
			$folder = "../../po_documents/qoutationDoc/";
			move_uploaded_file($file_temp, $folder.$$unique.".pdf");}
		}
		
		
		$crud   = new crud($table_details);
		$iii=explode('#>',$_POST['item_id']);
		$_POST['item_id']=$iii[1];
		$crud->insert();

}



if($$unique>0)

{

		$condition=$unique."=".$$unique;

		$data=db_fetch_object($table_master,$condition);

		while (list($key, $value)=each($data))

		{ $$key=$value;}

		

}

if($$unique>0) $btn_name='Update PO Information'; else $btn_name='Initiate PO Information';


if($_SESSION[$unique]<1)
$$unique=next_po_no();





//auto_complete_from_db($table,$show,$id,$con,$text_field_id);

auto_complete_from_db('item_info','item_name','concat(item_name,"#>",item_id)','1 and product_nature="Purchasable"','item_id');



?>
<script language="javascript">

function count()

{

var num=((document.getElementById('qty').value)*1)*((document.getElementById('rate').value)*1);

document.getElementById('amount').value = num.toFixed(2);	

}

</script>

<div class="form-container_large">
  <form action="?<?=$unique?>=<?=$$unique?>" enctype="multipart/form-data" method="post" name="codz" id="codz" >
    <table width="99%" border="0" cellspacing="0" cellpadding="0" align="center">
      <tr>
        <td valign="top"><fieldset>
          <? $field='po_no';?>
          <div>
            <label for="<?=$field?>">WO  No: </label>
            <input  name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>"/>
          </div>
          <? $field='po_date'; if($po_date=='') $po_date =date('Y-m-d');?>
          <div>
            <label for="<?=$field?>">WO Date:</label>
            <input  name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>" required/>
          </div>
         <? $field='group_for'; $table='user_group';$get_field='id';$show_field='group_name';?>
      <div>
        <label for="<?=$field?>">Concern:</label>
        <select id="<?=$field?>" name="<?=$field?>" required   onchange="getData2('ajax_vendor.php', 'vendor_space', this.value,  this.value)">
        <option></option>
        <? foreign_relation($table,$get_field,$show_field,$$field);?>
        </select>
      </div>
          <? $field='wo_del_date';?>
          <div>
            <label for="<?=$field?>">Delivery Date:</label>
            <input  name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>" />
          </div>
         
          <div>
            <? $field='tax';?>
            <label for="<?=$field?>">VAT:</label>
            <input  name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>" required/>
          </div>
		  
		   <div>
            <? $field='tax_ait';?>
            <label for="<?=$field?>">Tax/AIT:</label>
            <input  name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>" required/>
          </div>
         
          
          </fieldset></td>
        <td><fieldset>
          
          <div></div>
		  
		  
		  
          <? $field='po_subject';?>
          <div>
            <label for="<?=$field?>">Subject:</label>
            <input name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>" />
          </div>
		  
		   <? $field='po_details';?>
          <div>
            <label for="<?=$field?>">Remarks:</label>
            <input name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>" />
          </div>
		  
      <? $field='vendor_id2'; $table='vendor'; $get_field='vendor_id2'; $show_field='vendor_name'; ?>

      <div>

        <label for="<?=$field?>">Party:</label>

		<span id="vendor_space">
		
	
<input name="<?=$field?>" type="text" id="<?=$field?>" value="<?php if($vendor_id>0){ 

$vendor = find_all_field('vendor','','vendor_id='.$vendor_id);

echo $vendor->vendor_name; }?>" readonly="readonly" />
<input  name="vendor_id" type="hidden" id="vendor_id" value="<?=$vendor->vendor_id?>"/>	  	
		</span>      </div>
          <div>
          
		  
		  <? $field='payment_terms';?>
            <div>
              <label for="<?=$field?>">Payment Terms:</label>
              <select name="payment_terms" required id="payment_terms"  style="width:204px">
                <option value="">Select One</option>
                <? foreign_relation('payment_terms','terms_id','payment_terms',$payment_terms);?>
              </select>
            </div>
		  
		  
		  
		  
			<? $field='quotation_no';?>
            <div>
              <label for="<?=$field?>">Quotation No:</label>
              <input  name="<?=$field?>" type="text" id="<?=$field?>" value="<?=$$field?>"  />
            </div>
            
            
			<div>
            <label>Qoutation (*PDF) </label>
            <input name="qoutationDoc" type="file" id="qoutationDoc" style="height:19px;"/>
          </div>
          </div>
          </fieldset></td>
      </tr>
      <tr>
        <td colspan="2">&nbsp;</td>
      </tr>
    </table>
    <!--
  </form>

  <form action="?<?=$unique?>=<?=$$unique?>" method="post" name="cloud" id="cloud">-->

    <? 

$group_for = find_a_field('warehouse','group_for','warehouse_id='.$warehouse_id.' ');

if(($vendor->ledger_id==0)&&($group_for==2||$group_for==3)){ ?>
    <table width="80%" border="0" align="center" cellpadding="5" cellspacing="0">
      <tr>
        <td bgcolor="#FF3333"><div align="center" class="style1">VENDOR IS BLOCKED. NO ACCOUNT CODE FOUND</div></td>
      </tr>
    </table>
    <? }else{?>
    <table  width="100%" border="1" align="left"  style="border-collapse:collapse; border:1px solid #caf5a5;" cellpadding="2" cellspacing="2">
                      <tr>
                        <td height="30" align="center" bgcolor="#0099FF"><strong>Item Name</strong></td>
                        <td align="center" bgcolor="#0099FF"><strong>Stock</strong></td>
                        <td align="center" bgcolor="#0099FF"><strong>Unit</strong></td>
                        <td align="center" bgcolor="#0099FF"><strong>Price</strong></td>
                        <td align="center" bgcolor="#0099FF"><strong>Qty</strong></td>
                        <td align="center" bgcolor="#0099FF"><strong>Amount</strong></td>
                          <td  rowspan="2" align="center" bgcolor="#FF0000">
						  <div class="button">
						  <input name="add" type="submit" id="add" value="ADD" tabindex="12" class="update"/>                       
						  </div>				        </td>
      </tr>
                      <tr>
<td align="center" bgcolor="#CCCCCC">
<input  name="<?=$unique?>" type="hidden" id="<?=$unique?>" value="<?=$$unique?>"/>
<input  name="warehouse_id" type="hidden" id="warehouse_id" value="<?=$warehouse_id?>"/><!--
<input  name="po_date" type="hidden" id="po_date" value="<?=$po_date?>"/>
<input  name="vendor_id" type="hidden" id="vendor_id" value="<?=$vendor_id?>"/>
<input  name="group_for" type="hidden" id="group_for" value="<?=$group_for?>"/>-->
<input  name="item_id" type="text" id="item_id" value="<?=$item_id?>" style="width:320px;" required onblur="getData2('po_ajax.php', 'po',this.value,1 );"/></td>
<td colspan="3" align="center" bgcolor="#CCCCCC">
<span id="po">
<input name="stk" type="text" class="input3" id="stk" style="width:100px;" readonly="readonly"/>
<input name="unit" type="text" class="input3" id="unit" style="width:80px;" readonly="readonly"/>
<input name="price" type="text" class="input3" id="price" style="width:80px;"  readonly="readonly"/>
</span></td>
<td align="center" bgcolor="#CCCCCC"><input name="qty" type="text" class="input3" id="qty"  maxlength="100" style="width:90px;" onchange="count()" required/></td>
<td align="center" bgcolor="#CCCCCC"><input name="amount" type="text" class="input3" id="amount" style="width:100px;" /></td>
      </tr>
    </table>
    <? }?>
    <br />
    <br />
    <br />
    <br />
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="tabledesign2">
            <? 

$res='select a.id,concat(b.item_name) as item_name, a.unit_name, a.qty , a.rate as unit_price, a.amount,"x" from purchase_invoice a,item_info b where b.item_id=a.item_id and a.po_no='.$po_no;
echo link_report_add_del_auto($res,'',6,0);

?>
          </div></td>
      </tr>
      <tr>
        <td></td>
      </tr>
    </table>

  </form>
  <? if($_SESSION[$unique]>0){?>
  <br />
  
  <form action="" method="post" name="cz" id="cz" >
    <table width="100%" border="0">
      <tr>
        <td align="center"><input name="delete"  type="submit" class="btn1" value="DELETE AND CANCEL PO" style="width:270px; font-weight:bold; font-size:12px;color:#F00; height:30px" />
        </td>
        <td align="center"><input name="confirmm" type="submit" class="btn1" value="CONFIRM AND FORWARD PO" style="width:270px; float:right; font-weight:bold; font-size:12px; height:30px; color:#FFF" />
        </td>
      </tr>
    </table>
  </form>
  <? }?>
</div>
<script>$("#codz").validate();$("#cloud").validate();</script>
<script>
  $( function() {
    $( "#item_del_date" ).datepicker({
      changeMonth: true,
      changeYear: true,
	  dateFormat: 'yy-mm-dd'
    });
	$( "#delivery_within" ).datepicker({
      changeMonth: true,
      changeYear: true,
	  dateFormat: 'yy-mm-dd'
    });
  } );
  </script>
<?

require_once "../../../assets/template/layout.bottom.php";

?>
