<?

//


 

 

require_once "../../../controllers/routing/default_values.php";
require_once SERVER_CORE."routing/layout.top.php";

$pi_id = $_REQUEST['id'];

$app_date = $_REQUEST['app_date'];

$app_val = $_REQUEST['val'];
 
$pi_data = find_all_field('pi_master','','id="'.$pi_id.'"');

$marketing_person = find_a_field('pi_details','marketing_person','pi_id='.$pi_id);

$pi_type = find_a_field('pi_type','pi_type','id='.$pi_data->pi_type);

$merchandizer_code = find_a_field('pi_details','merchandizer_code','pi_id='.$pi_id);

$merchandizer_email = find_a_field('merchandizer_info','email','merchandizer_code='.$merchandizer_code);

//$pi_creator_email = find_a_field('user_activity_management','email','user_id='.$pi_data->entry_by);

$pi_creator_email = find_a_field('marketing_person','email','person_code='.$marketing_person);

$pi_found = find_a_field('pi_mail_forwarding','count(merchandiser_code)','merchandiser_code='.$merchandizer_code);

$checked_by = $_SESSION['user']['id'];
$checked_at=date('Y-m-d H:i:s');
 
 if ($app_val==1) {



   $YR = date('Y',strtotime($app_date));
   $year = date('y',strtotime($app_date));
   $month = date('m',strtotime($app_date));
   $digital_sign_id = find_a_field('management_approval_history','max(digital_sign_id)','year="'.$YR.'"')+1;
   $cy_id = sprintf("%08d", $digital_sign_id);
   $digital_sign=$year.''.$month.''.$cy_id;

	$status = 'CHECKED';
	


	 $flag = $_REQUEST['flag'];



			 $new_sql="UPDATE pi_master SET status='".$status."', digital_sign_id = '".$digital_sign_id."', digital_sign = '".$digital_sign."', 
			 checked_by = '".$checked_by."', checked_at = '".$checked_at."' WHERE id = '".$pi_id."'";
			 db_query($new_sql);
			 
	
			 
			 

	$am_ins = "INSERT INTO management_approval_history (app_date, tr_no, tr_no_view, tr_date, tr_type, year, digital_sign_id, digital_sign, checked_by, checked_at)
  
  VALUES('".$app_date."', '".$pi_id."', '".$pi_data->pi_no."', '".$pi_data->pi_date."', '".$pi_type."', '".$YR."', '".$digital_sign_id."', '".$digital_sign."', 
  '".$checked_by."',  '".$checked_at."')";

db_query($am_ins);



$emailId = '';

//$emailId = 'omar.fk15@gmail.com';

$emailId = $merchandizer_email;

if($emailId!=''){

$to = $emailId;

$from = 'info@boxes.com.bd';

$subject = "New PI approval. PI No is: ".$pi_data->pi_no." ";

$txt = "
<p>From NATIVE PACKAGES LTD.</p>

<p>Dear Sir,</p>

<p>Good Day</p>

<p>A new PI has been created. Need your approval. PI No is: <b>".$pi_data->pi_no."<b></p>

<p>Prepared By- <b>".find_a_field('user_activity_management','fname','user_id='.$pi_data->entry_by)."<b></p>

<p>URL: <b>https://boxes.com.bd/NATIVE/buyer_mod/pages/main/index.php?module_id=12<b></p> 

<p>This EMAIL is automatically generated by ERP Software.</p>

<p>If have any problem please contact with NPL Marketing Team: 01401140108</p>
<p>First Time Access login, Currently Your user Id is your receiving  mail ID and Password is 12345, please change your password after system login.</p>";

$headers  = 'MIME-Version: 1.0' . "\n";

$headers .= 'Cc: m.islam@nassa.com.bd' . "\n";

$headers .= 'Cc: sk.sarwar@nassagroup.org' . "\n";

$headers .= 'Cc: ' .$pi_creator_email. "\n";

$headers .= 'Content-type:text/html;charset=UTF-8' . "\n";


$ok = @mail($to, $subject, $txt, $headers, "-f " . $from);   


$mail_forw = "INSERT INTO pi_mail_forwarding (app_date, tr_no, tr_no_view, tr_date, merchandiser_code, merchandiser_email, pi_creator_email, checked_by, checked_at)
  
VALUES('".$app_date."', '".$pi_id."', '".$pi_data->pi_no."', '".$pi_data->pi_date."',  '".$merchandizer_code."', '".$merchandizer_email."', '".$pi_creator_email."', '".$checked_by."', '".$checked_at."')";

db_query($mail_forw);


}


//"
//. if ($pi_found == 0){
//"<p>Note: Your id is <b>".$merchandizer_email."<b> & your temporary password is 12345, please change your password and saved your password for next access.</p>"
// } . "


	

} elseif ($app_val==2) {


 $up_h="UPDATE pi_master SET mis_hold='No' WHERE id = '".$pi_id."'";
db_query($up_h);

 $hr_ins = "INSERT INTO mis_hold_reject_history (app_date, tr_no, tr_no_view, tr_date, tr_type,  tr_from, checked_by, checked_at)
  
  VALUES('".$app_date."', '".$pi_id."', '".$pi_data->pi_no."', '".$pi_data->pi_date."',  'Unhold', '".$pi_type."', 
  '".$checked_by."',  '".$checked_at."')";
db_query($hr_ins);

}  elseif ($app_val==3) {

 $up_h="UPDATE pi_master SET mis_hold='Yes' WHERE id = '".$pi_id."'";
db_query($up_h);

 $hr_ins = "INSERT INTO mis_hold_reject_history (app_date, tr_no, tr_no_view, tr_date, tr_type,  tr_from, checked_by, checked_at)
  
  VALUES('".$app_date."', '".$pi_id."', '".$pi_data->pi_no."', '".$pi_data->pi_date."',  'Hold', '".$pi_type."', 
  '".$checked_by."',  '".$checked_at."')";
db_query($hr_ins);

}elseif  ($app_val==4){

$up_c ="UPDATE pi_master SET mis_reject='Yes', status='MANUAL' WHERE id = '".$pi_id."'";
db_query($up_c);

$hr_ins = "INSERT INTO mis_hold_reject_history (app_date, tr_no, tr_no_view, tr_date, tr_type,  tr_from, checked_by, checked_at)
  
  VALUES('".$app_date."', '".$pi_id."', '".$pi_data->pi_no."', '".$pi_data->pi_date."',  'Reject', '".$pi_type."', 
  '".$checked_by."',  '".$checked_at."')";
db_query($hr_ins);

}





echo 'Success!';


?>